name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
    
    - name: Build with Nuitka
      run: |
        cd src
        python -m nuitka --standalone --windows-console-mode=disable --include-package=tkinter --windows-icon-from-ico=busylight.ico --output-dir=build --assume-yes-for-downloads --enable-plugin=tk-inter busylight.py
    
    - name: List build directory contents
      run: |
        cd src
        Get-ChildItem -Path build -Recurse | Select-Object FullName
    
    - name: Create ZIP archive
      run: |
        cd src/build
        Compress-Archive -Path busylight.dist/* -DestinationPath BusyLight-Windows.zip
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: BusyLight-Windows-Executable
        path: src/build/busylight.dist/busylight.exe
        
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: BusyLight-Windows-Package
        path: src/build/BusyLight-Windows.zip
