name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        cd src
        python -m nuitka --standalone --windows-console-mode=disable --include-package=tkinter --include-package=PIL --include-package=pystray --windows-icon-from-ico=../assets/busylight.ico --output-dir=build --output-filename=busylight.exe --assume-yes-for-downloads --enable-plugin=tk-inter main.py
    
    - name: List build directory contents
      run: |
        cd src
        Get-ChildItem -Path build -Recurse | Select-Object FullName
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: busylight-executable
        path: src/build/main.dist/busylight.exe
        
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: busylight
        path: src/build/main.dist/
